apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
helmCharts:
  - name: kiali-server
    repo: https://kiali.org/helm-charts
    version: ${ARGOCD_ENV_kiali_version}
    releaseName: kiali
    namespace: istio-system
