deployment:
  replicas: ${ARGOCD_ENV_kiali_replicas}
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_kiali_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_kiali_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_kiali_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_kiali_limits_memory}"
  security_context:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

external_services:
  istio:
    root_namespace: istio-system
