---
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: envsubstappofapp
spec:
  allowConcurrency: true
  generate:
    command:
      - /home/argocd/cmp-server/scripts/envsubstappofapp.sh
---
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: envsubst
spec:
  allowConcurrency: true
  generate:
    command:
      - /home/argocd/cmp-server/scripts/envsubst.sh

