apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-gateways
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.5.1/standard-install.yaml
  - keep-alive.yaml
  - proxy-security-headers.yaml
helmCharts:
  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.29.2
    releaseName: istio-gateways
    namespace: istio-gateways
