apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-gateways
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.5.1/standard-install.yaml
  - keep-alive.yaml
helmCharts:
  - name: istio-gateways
    repo: https://kubernetes-sigs.github.io/istio-gateways
    releaseName: istio-gateways
    namespace: istio-gateways
