apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
  name: istio-gateways-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: gitops/apps/istio/istio-gateways
    repoURL: "https://github.com/KhaledSaiidi/kube-signal.git"
    targetRevision: HEAD

  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 12
      backoff:
        duration: 3s
        maxDuration: 7m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
