apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: istio-ingress-gateway-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: gitops/apps/istio/istio-ingress-gateway
    repoURL: ${ARGOCD_ENV_gitops_root_app_repo_url}
    targetRevision: ${ARGOCD_ENV_gitops_root_app_target_revision}
    plugin:
      name: envsubst
      env:
        - name: istio_ingress_gateway_version
          value: "${ARGOCD_ENV_istio_ingress_gateway_version}"

  destination:
    namespace: istio-ingress-gateway
    server: https://kubernetes.default.svc
  project: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
