apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: public-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: gitops/apps/istio/public-gateway
    repoURL: ${ARGOCD_ENV_gitops_root_app_repo_url}
    targetRevision: ${ARGOCD_ENV_gitops_root_app_target_revision}
    plugin:
      name: envsubst
      env:
        - name: base_domain
          value: "${ARGOCD_ENV_base_domain}"
        - name: public_gateway_dns_target
          value: "${ARGOCD_ENV_public_gateway_dns_target}"
        - name: public_gateway_replicas
          value: "${ARGOCD_ENV_public_gateway_replicas}"
        - name: public_gateway_min_replicas
          value: "${ARGOCD_ENV_public_gateway_min_replicas}"
        - name: public_gateway_max_replicas
          value: "${ARGOCD_ENV_public_gateway_max_replicas}"
        - name: resource_public_gateway_requests_cpu
          value: "${ARGOCD_ENV_resource_public_gateway_requests_cpu}"
        - name: resource_public_gateway_requests_memory
          value: "${ARGOCD_ENV_resource_public_gateway_requests_memory}"
        - name: resource_public_gateway_limits_cpu
          value: "${ARGOCD_ENV_resource_public_gateway_limits_cpu}"
        - name: resource_public_gateway_limits_memory
          value: "${ARGOCD_ENV_resource_public_gateway_limits_memory}"
  destination:
    namespace: istio-ingress
    server: https://kubernetes.default.svc
  project: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
