apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/istio-main.yaml
  - ../../../base/kyverno.yaml
  - ../../../base/metallb.yaml
  - ../../../base/cert-manager.yaml
