x-all-tolerations: &allTolerations
  - operator: Exists

deploymentMode: SimpleScalable

global:
  extraEnvFrom:
    - secretRef:
        name: loki-garage-s3

defaults:
  podAnnotations:
    sidecar.istio.io/inject: "false"
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: loki-garage-s3

loki:
  auth_enabled: false
  structuredConfig:
    common:
      storage:
        s3:
          bucketnames: loki-chunks
          endpoint: "http://garage.garage.svc.cluster.local:3900"
          region: '{{ "$" }}{AWS_REGION}'
          access_key_id: '{{ "$" }}{AWS_ACCESS_KEY_ID}'
          secret_access_key: '{{ "$" }}{AWS_SECRET_ACCESS_KEY}'
          s3forcepathstyle: true
          insecure: true
    ruler:
      storage:
        type: s3
        s3:
          bucketnames: loki-ruler
          endpoint: "http://garage.garage.svc.cluster.local:3900"
          region: '{{ "$" }}{AWS_REGION}'
          access_key_id: '{{ "$" }}{AWS_ACCESS_KEY_ID}'
          secret_access_key: '{{ "$" }}{AWS_SECRET_ACCESS_KEY}'
          s3forcepathstyle: true
          insecure: true
  commonConfig:
    replication_factor: ${ARGOCD_ENV_observability_loki_replication_factor}
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: ${ARGOCD_ENV_observability_loki_schema_period}
  limits_config:
    allow_structured_metadata: true
    retention_period: ${ARGOCD_ENV_observability_loki_retention_period}
    ingestion_rate_mb: ${ARGOCD_ENV_observability_loki_ingestion_rate_mb}
    ingestion_burst_size_mb: ${ARGOCD_ENV_observability_loki_ingestion_burst_size_mb}
    max_query_parallelism: ${ARGOCD_ENV_observability_loki_max_query_parallelism}
    split_queries_by_interval: ${ARGOCD_ENV_observability_loki_split_queries_by_interval}
    volume_enabled: true
  compactor:
    retention_enabled: true
    delete_request_store: s3
  ruler:
    enable_api: true
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:
      endpoint: '"http://garage.garage.svc.cluster.local:3900"'
      region: garage
      accessKeyId: placeholder
      secretAccessKey: placeholder
      s3ForcePathStyle: true
      insecure: true

singleBinary:
  replicas: ${ARGOCD_ENV_loki_single_binary_replicas}

read:
  replicas: ${ARGOCD_ENV_loki_read_replicas}
  persistence:
    size: 10Gi
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_loki_read_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_loki_read_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_loki_read_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_loki_read_limits_memory}"
  tolerations: *allTolerations

write:
  replicas: ${ARGOCD_ENV_loki_write_replicas}
  persistence:
    size: 20Gi
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_loki_write_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_loki_write_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_loki_write_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_loki_write_limits_memory}"
  tolerations: *allTolerations

backend:
  replicas: ${ARGOCD_ENV_loki_backend_replicas}
  sidecar: false
  persistence:
    size: 20Gi
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_loki_backend_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_loki_backend_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_loki_backend_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_loki_backend_limits_memory}"
  tolerations: *allTolerations

gateway:
  replicas: ${ARGOCD_ENV_loki_gateway_replicas}
  podAnnotations:
    sidecar.istio.io/inject: "false"
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_loki_gateway_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_loki_gateway_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_loki_gateway_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_loki_gateway_limits_memory}"
  tolerations: *allTolerations

lokiCanary:
  podAnnotations:
    sidecar.istio.io/inject: "false"
  tolerations: *allTolerations
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_loki_canary_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_loki_canary_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_loki_canary_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_loki_canary_limits_memory}"

chunksCache:
  enabled: true
  replicas: ${ARGOCD_ENV_loki_chunks_cache_replicas}
  podAnnotations:
    sidecar.istio.io/inject: "false"
  allocatedMemory: 512
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_loki_chunks_cache_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_loki_chunks_cache_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_loki_chunks_cache_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_loki_chunks_cache_limits_memory}"
  tolerations: *allTolerations

resultsCache:
  enabled: true
  replicas: ${ARGOCD_ENV_loki_results_cache_replicas}
  podAnnotations:
    sidecar.istio.io/inject: "false"
  allocatedMemory: 256
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_loki_results_cache_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_loki_results_cache_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_loki_results_cache_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_loki_results_cache_limits_memory}"
  tolerations: *allTolerations

memcachedExporter:
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_loki_memcached_exporter_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_loki_memcached_exporter_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_loki_memcached_exporter_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_loki_memcached_exporter_limits_memory}"
