x-all-tolerations: &allTolerations
  - operator: Exists

x-tempo-extra-args: &tempoExtraArgs
  - -config.expand-env=true

global:
  extraEnvFrom:
    - secretRef:
        name: tempo-garage-s3

tempo:
  podAnnotations:
    sidecar.istio.io/inject: "false"

multitenancyEnabled: false

traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true

storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-traces
      endpoint: garage.garage.svc.cluster.local:3900
      access_key: '{{ "$" }}{AWS_ACCESS_KEY_ID}'
      secret_key: '{{ "$" }}{AWS_SECRET_ACCESS_KEY}'
      region: '{{ "$" }}{AWS_REGION}'
      forcepathstyle: true
      insecure: true

ingester:
  replicas: ${ARGOCD_ENV_tempo_ingester_replicas}
  extraArgs: *tempoExtraArgs
  config:
    replication_factor: ${ARGOCD_ENV_observability_tempo_ingester_replication_factor}
    trace_idle_period: ${ARGOCD_ENV_observability_tempo_trace_idle_period}
    max_block_bytes: ${ARGOCD_ENV_observability_tempo_max_block_bytes}
    max_block_duration: ${ARGOCD_ENV_observability_tempo_max_block_duration}
    complete_block_timeout: ${ARGOCD_ENV_observability_tempo_complete_block_timeout}
    flush_all_on_shutdown: true
  persistence:
    enabled: true
    size: 20Gi
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_tempo_ingester_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_tempo_ingester_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_tempo_ingester_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_tempo_ingester_limits_memory}"
  tolerations: *allTolerations

distributor:
  replicas: ${ARGOCD_ENV_tempo_distributor_replicas}
  extraArgs: *tempoExtraArgs
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_tempo_distributor_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_tempo_distributor_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_tempo_distributor_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_tempo_distributor_limits_memory}"
  tolerations: *allTolerations

querier:
  replicas: ${ARGOCD_ENV_tempo_querier_replicas}
  extraArgs: *tempoExtraArgs
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_tempo_querier_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_tempo_querier_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_tempo_querier_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_tempo_querier_limits_memory}"
  tolerations: *allTolerations

queryFrontend:
  replicas: ${ARGOCD_ENV_tempo_query_frontend_replicas}
  extraArgs: *tempoExtraArgs
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_tempo_query_frontend_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_tempo_query_frontend_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_tempo_query_frontend_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_tempo_query_frontend_limits_memory}"
  tolerations: *allTolerations

compactor:
  replicas: ${ARGOCD_ENV_tempo_compactor_replicas}
  extraArgs: *tempoExtraArgs
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_tempo_compactor_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_tempo_compactor_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_tempo_compactor_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_tempo_compactor_limits_memory}"
  tolerations: *allTolerations

gateway:
  replicas: ${ARGOCD_ENV_tempo_gateway_replicas}
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_tempo_gateway_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_tempo_gateway_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_tempo_gateway_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_tempo_gateway_limits_memory}"
  tolerations: *allTolerations

memcached:
  replicas: ${ARGOCD_ENV_tempo_memcached_replicas}
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_tempo_memcached_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_tempo_memcached_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_tempo_memcached_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_tempo_memcached_limits_memory}"
  tolerations: *allTolerations
