apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-kube-forge-com
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  secretName: wildcard-kube-forge-com-tls
  issuerRef:
    name: letsencrypt-prod-route53
    kind: ClusterIssuer
  dnsNames:
    - "*.kube-forge.com"
    - kube-forge.com
