apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "app-domain-certificate"
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  secretName: "wildcard-domain-secret-tls"
  issuerRef:
    name: letsencrypt-prod-route53
    kind: ClusterIssuer
  dnsNames:
    - "*.${ARGOCD_ENV_base_domain}"
    - "${ARGOCD_ENV_base_domain}"
