crds:
  enabled: true

replicaCount: ${ARGOCD_ENV_cert_manager_replicas}

podDisruptionBudget:
  enabled: true
  minAvailable: 1

prometheus:
  enabled: true

resources:
  requests:
    cpu: "${ARGOCD_ENV_resource_cert_manager_requests_cpu}"
    memory: "${ARGOCD_ENV_resource_cert_manager_requests_memory}"
  limits:
    cpu: "${ARGOCD_ENV_resource_cert_manager_limits_cpu}"
    memory: "${ARGOCD_ENV_resource_cert_manager_limits_memory}"

securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

global:
  leaderElection:
    namespace: cert-manager

webhook:
  replicaCount: ${ARGOCD_ENV_cert_manager_webhook_replicas}
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_cert_manager_webhook_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_cert_manager_webhook_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_cert_manager_webhook_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_cert_manager_webhook_limits_memory}"
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true

cainjector:
  replicaCount: ${ARGOCD_ENV_cert_manager_cainjector_replicas}
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_cert_manager_cainjector_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_cert_manager_cainjector_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_cert_manager_cainjector_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_cert_manager_cainjector_limits_memory}"
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true

startupapicheck:
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_cert_manager_startupapicheck_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_cert_manager_startupapicheck_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_cert_manager_startupapicheck_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_cert_manager_startupapicheck_limits_memory}"
