apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: applications
  namespace: observability
spec:
  allowCrossNamespaceImport: false
  instanceSelector:
    matchLabels:
      dashboards: grafana
  resyncPeriod: 10m0s
  title: Applications
  uid: applications
