apiVersion: v1
kind: ConfigMap
metadata:
  name: public-gateway-infrastructure
  namespace: istio-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "10"
data:
  service: |
    spec:
      type: LoadBalancer
      externalTrafficPolicy: Cluster
  deployment: |
    spec:
      replicas: ${ARGOCD_ENV_public_gateway_replicas}
      template:
        metadata:
          labels:
            app: istio-ingress-gateway
            istio: ingressgateway
        spec:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app: istio-ingress-gateway
          containers:
            - name: istio-proxy
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  cpu: 1000m
                  memory: 512Mi
  horizontalPodAutoscaler: |
    spec:
      minReplicas: ${ARGOCD_ENV_public_gateway_min_replicas}
      maxReplicas: ${ARGOCD_ENV_public_gateway_max_replicas}
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 80
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 80
  podDisruptionBudget: |
    spec:
      minAvailable: 1
