apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: platform-baseline
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: ${ARGOCD_ENV_gitops_root_app_repo_url}
    targetRevision: ${ARGOCD_ENV_gitops_root_app_target_revision}
    path: gitops/apps/argocd
    plugin:
      name: envsubst
      env:
        - name: argocd_chart_version
          value: "${ARGOCD_ENV_argocd_chart_version}"
        - name: argocd_server_service_type
          value: "${ARGOCD_ENV_argocd_server_service_type}"
        - name: argocd_reconciliation_timeout
          value: "${ARGOCD_ENV_argocd_reconciliation_timeout}"
        - name: argocd_exec_timeout
          value: "${ARGOCD_ENV_argocd_exec_timeout}"
        - name: argocd_repo_server_timeout_secs
          value: "${ARGOCD_ENV_argocd_repo_server_timeout_secs}"
        - name: argocd_cmp_image
          value: "${ARGOCD_ENV_argocd_cmp_image}"
        - name: base_domain
          value: "${ARGOCD_ENV_base_domain}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
