apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-20'
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: platform-baseline
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: ${ARGOCD_ENV_gitops_root_app_repo_url}
    targetRevision: ${ARGOCD_ENV_gitops_root_app_target_revision}
    path: gitops/apps/cert-manager
    plugin:
      name: envsubst
      env:
        - name: cert_manager_acme_email
          value: "${ARGOCD_ENV_cert_manager_acme_email}"
        - name: cert_manager_route53_region
          value: "${ARGOCD_ENV_cert_manager_route53_region}"
        - name: cert_manager_route53_hosted_zone_id
          value: "${ARGOCD_ENV_cert_manager_route53_hosted_zone_id}"
        - name: base_domain
          value: "${ARGOCD_ENV_base_domain}"
        - name: cert_manager_version
          value: "${ARGOCD_ENV_cert_manager_version}"
        - name: cert_manager_replicas
          value: "${ARGOCD_ENV_cert_manager_replicas}"
        - name: cert_manager_webhook_replicas
          value: "${ARGOCD_ENV_cert_manager_webhook_replicas}"
        - name: cert_manager_cainjector_replicas
          value: "${ARGOCD_ENV_cert_manager_cainjector_replicas}"
        - name: resource_cert_manager_requests_cpu
          value: "${ARGOCD_ENV_resource_cert_manager_requests_cpu}"
        - name: resource_cert_manager_requests_memory
          value: "${ARGOCD_ENV_resource_cert_manager_requests_memory}"
        - name: resource_cert_manager_limits_cpu
          value: "${ARGOCD_ENV_resource_cert_manager_limits_cpu}"
        - name: resource_cert_manager_limits_memory
          value: "${ARGOCD_ENV_resource_cert_manager_limits_memory}"
        - name: resource_cert_manager_webhook_requests_cpu
          value: "${ARGOCD_ENV_resource_cert_manager_webhook_requests_cpu}"
        - name: resource_cert_manager_webhook_requests_memory
          value: "${ARGOCD_ENV_resource_cert_manager_webhook_requests_memory}"
        - name: resource_cert_manager_webhook_limits_cpu
          value: "${ARGOCD_ENV_resource_cert_manager_webhook_limits_cpu}"
        - name: resource_cert_manager_webhook_limits_memory
          value: "${ARGOCD_ENV_resource_cert_manager_webhook_limits_memory}"
        - name: resource_cert_manager_cainjector_requests_cpu
          value: "${ARGOCD_ENV_resource_cert_manager_cainjector_requests_cpu}"
        - name: resource_cert_manager_cainjector_requests_memory
          value: "${ARGOCD_ENV_resource_cert_manager_cainjector_requests_memory}"
        - name: resource_cert_manager_cainjector_limits_cpu
          value: "${ARGOCD_ENV_resource_cert_manager_cainjector_limits_cpu}"
        - name: resource_cert_manager_cainjector_limits_memory
          value: "${ARGOCD_ENV_resource_cert_manager_cainjector_limits_memory}"
        - name: resource_cert_manager_startupapicheck_requests_cpu
          value: "${ARGOCD_ENV_resource_cert_manager_startupapicheck_requests_cpu}"
        - name: resource_cert_manager_startupapicheck_requests_memory
          value: "${ARGOCD_ENV_resource_cert_manager_startupapicheck_requests_memory}"
        - name: resource_cert_manager_startupapicheck_limits_cpu
          value: "${ARGOCD_ENV_resource_cert_manager_startupapicheck_limits_cpu}"
        - name: resource_cert_manager_startupapicheck_limits_memory
          value: "${ARGOCD_ENV_resource_cert_manager_startupapicheck_limits_memory}"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
