apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: garage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: gitops/apps/garage
    repoURL: ${ARGOCD_ENV_gitops_root_app_repo_url}
    targetRevision: ${ARGOCD_ENV_gitops_root_app_target_revision}
    plugin:
      name: envsubst
      env:
        - name: garage_version
          value: "${ARGOCD_ENV_garage_version}"
        - name: base_domain
          value: "${ARGOCD_ENV_base_domain}"
        - name: garage_replication_factor
          value: "${ARGOCD_ENV_garage_replication_factor}"
        - name: garage_replicas
          value: "${ARGOCD_ENV_garage_replicas}"
        - name: resource_garage_requests_cpu
          value: "${ARGOCD_ENV_resource_garage_requests_cpu}"
        - name: resource_garage_requests_memory
          value: "${ARGOCD_ENV_resource_garage_requests_memory}"
        - name: resource_garage_limits_cpu
          value: "${ARGOCD_ENV_resource_garage_limits_cpu}"
        - name: resource_garage_limits_memory
          value: "${ARGOCD_ENV_resource_garage_limits_memory}"
        - name: resource_garage_bootstrap_job_requests_cpu
          value: "${ARGOCD_ENV_resource_garage_bootstrap_job_requests_cpu}"
        - name: resource_garage_bootstrap_job_requests_memory
          value: "${ARGOCD_ENV_resource_garage_bootstrap_job_requests_memory}"
        - name: resource_garage_bootstrap_job_limits_cpu
          value: "${ARGOCD_ENV_resource_garage_bootstrap_job_limits_cpu}"
        - name: resource_garage_bootstrap_job_limits_memory
          value: "${ARGOCD_ENV_resource_garage_bootstrap_job_limits_memory}"
        - name: resource_garage_backup_lifecycle_job_requests_cpu
          value: "${ARGOCD_ENV_resource_garage_backup_lifecycle_job_requests_cpu}"
        - name: resource_garage_backup_lifecycle_job_requests_memory
          value: "${ARGOCD_ENV_resource_garage_backup_lifecycle_job_requests_memory}"
        - name: resource_garage_backup_lifecycle_job_limits_cpu
          value: "${ARGOCD_ENV_resource_garage_backup_lifecycle_job_limits_cpu}"
        - name: resource_garage_backup_lifecycle_job_limits_memory
          value: "${ARGOCD_ENV_resource_garage_backup_lifecycle_job_limits_memory}"
  destination:
    namespace: garage
    server: https://kubernetes.default.svc
  project: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
