apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: istio-main
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: gitops/argo-apps/base/istio
    repoURL: ${ARGOCD_ENV_gitops_root_app_repo_url}
    targetRevision: ${ARGOCD_ENV_gitops_root_app_target_revision}
    plugin:
      name: envsubst
      env:
        - name: gitops_root_app_repo_url
          value: "${ARGOCD_ENV_gitops_root_app_repo_url}"
        - name: gitops_root_app_target_revision
          value: "${ARGOCD_ENV_gitops_root_app_target_revision}"
        - name: istio_main_version
          value: "${ARGOCD_ENV_istio_main_version}"
        - name: gateway_api_version
          value: "${ARGOCD_ENV_gateway_api_version}"
        - name: base_domain
          value: "${ARGOCD_ENV_base_domain}"
        - name: kiali_version
          value: "${ARGOCD_ENV_kiali_version}"
        - name: istiod_replicas
          value: "${ARGOCD_ENV_istiod_replicas}"
        - name: public_gateway_replicas
          value: "${ARGOCD_ENV_public_gateway_replicas}"
        - name: public_gateway_min_replicas
          value: "${ARGOCD_ENV_public_gateway_min_replicas}"
        - name: public_gateway_max_replicas
          value: "${ARGOCD_ENV_public_gateway_max_replicas}"
        - name: kiali_replicas
          value: "${ARGOCD_ENV_kiali_replicas}"
        - name: resource_istiod_requests_cpu
          value: "${ARGOCD_ENV_resource_istiod_requests_cpu}"
        - name: resource_istiod_requests_memory
          value: "${ARGOCD_ENV_resource_istiod_requests_memory}"
        - name: resource_istiod_limits_cpu
          value: "${ARGOCD_ENV_resource_istiod_limits_cpu}"
        - name: resource_istiod_limits_memory
          value: "${ARGOCD_ENV_resource_istiod_limits_memory}"
        - name: resource_public_gateway_requests_cpu
          value: "${ARGOCD_ENV_resource_public_gateway_requests_cpu}"
        - name: resource_public_gateway_requests_memory
          value: "${ARGOCD_ENV_resource_public_gateway_requests_memory}"
        - name: resource_public_gateway_limits_cpu
          value: "${ARGOCD_ENV_resource_public_gateway_limits_cpu}"
        - name: resource_public_gateway_limits_memory
          value: "${ARGOCD_ENV_resource_public_gateway_limits_memory}"
        - name: resource_kiali_requests_cpu
          value: "${ARGOCD_ENV_resource_kiali_requests_cpu}"
        - name: resource_kiali_requests_memory
          value: "${ARGOCD_ENV_resource_kiali_requests_memory}"
        - name: resource_kiali_limits_cpu
          value: "${ARGOCD_ENV_resource_kiali_limits_cpu}"
        - name: resource_kiali_limits_memory
          value: "${ARGOCD_ENV_resource_kiali_limits_memory}"
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
