apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - openebs.yaml
  - metallb.yaml
  - istio-main.yaml
  - stateful-operator.yaml
  - stateful-resources.yaml
  - external-dns.yaml
  - kyverno.yaml
  - garage.yaml
  - reflector.yaml
