apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: platform-baseline
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: ${ARGOCD_ENV_gitops_root_app_repo_url}
    targetRevision: ${ARGOCD_ENV_gitops_root_app_target_revision}
    path: gitops/apps/kyverno
    plugin:
      name: envsubst
      env:
        - name: kyverno_version
          value: "${ARGOCD_ENV_kyverno_version}"
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/labels
        - /metadata/managedFields
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
