apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/part-of: platform-baseline
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: ${ARGOCD_ENV_gitops_root_app_repo_url}
    targetRevision: ${ARGOCD_ENV_gitops_root_app_target_revision}
    path: gitops/apps/metallb
    plugin:
      name: envsubst
      env:
        - name: addresses_start
          value: "${ARGOCD_ENV_metallb_config_addresses_start}"
        - name: addresses_end
          value: "${ARGOCD_ENV_metallb_config_addresses_end}"
        - name: metallb_version
          value: "${ARGOCD_ENV_metallb_version}"
        - name: resource_metallb_controller_requests_cpu
          value: "${ARGOCD_ENV_resource_metallb_controller_requests_cpu}"
        - name: resource_metallb_controller_requests_memory
          value: "${ARGOCD_ENV_resource_metallb_controller_requests_memory}"
        - name: resource_metallb_controller_limits_cpu
          value: "${ARGOCD_ENV_resource_metallb_controller_limits_cpu}"
        - name: resource_metallb_controller_limits_memory
          value: "${ARGOCD_ENV_resource_metallb_controller_limits_memory}"
        - name: resource_metallb_speaker_requests_cpu
          value: "${ARGOCD_ENV_resource_metallb_speaker_requests_cpu}"
        - name: resource_metallb_speaker_requests_memory
          value: "${ARGOCD_ENV_resource_metallb_speaker_requests_memory}"
        - name: resource_metallb_speaker_limits_cpu
          value: "${ARGOCD_ENV_resource_metallb_speaker_limits_cpu}"
        - name: resource_metallb_speaker_limits_memory
          value: "${ARGOCD_ENV_resource_metallb_speaker_limits_memory}"
        - name: resource_metallb_frr_requests_cpu
          value: "${ARGOCD_ENV_resource_metallb_frr_requests_cpu}"
        - name: resource_metallb_frr_requests_memory
          value: "${ARGOCD_ENV_resource_metallb_frr_requests_memory}"
        - name: resource_metallb_frr_limits_cpu
          value: "${ARGOCD_ENV_resource_metallb_frr_limits_cpu}"
        - name: resource_metallb_frr_limits_memory
          value: "${ARGOCD_ENV_resource_metallb_frr_limits_memory}"
        - name: resource_metallb_reloader_requests_cpu
          value: "${ARGOCD_ENV_resource_metallb_reloader_requests_cpu}"
        - name: resource_metallb_reloader_requests_memory
          value: "${ARGOCD_ENV_resource_metallb_reloader_requests_memory}"
        - name: resource_metallb_reloader_limits_cpu
          value: "${ARGOCD_ENV_resource_metallb_reloader_limits_cpu}"
        - name: resource_metallb_reloader_limits_memory
          value: "${ARGOCD_ENV_resource_metallb_reloader_limits_memory}"
        - name: resource_metallb_frr_metrics_requests_cpu
          value: "${ARGOCD_ENV_resource_metallb_frr_metrics_requests_cpu}"
        - name: resource_metallb_frr_metrics_requests_memory
          value: "${ARGOCD_ENV_resource_metallb_frr_metrics_requests_memory}"
        - name: resource_metallb_frr_metrics_limits_cpu
          value: "${ARGOCD_ENV_resource_metallb_frr_metrics_limits_cpu}"
        - name: resource_metallb_frr_metrics_limits_memory
          value: "${ARGOCD_ENV_resource_metallb_frr_metrics_limits_memory}"
        - name: resource_metallb_cp_frr_files_requests_cpu
          value: "${ARGOCD_ENV_resource_metallb_cp_frr_files_requests_cpu}"
        - name: resource_metallb_cp_frr_files_requests_memory
          value: "${ARGOCD_ENV_resource_metallb_cp_frr_files_requests_memory}"
        - name: resource_metallb_cp_frr_files_limits_cpu
          value: "${ARGOCD_ENV_resource_metallb_cp_frr_files_limits_cpu}"
        - name: resource_metallb_cp_frr_files_limits_memory
          value: "${ARGOCD_ENV_resource_metallb_cp_frr_files_limits_memory}"
        - name: resource_metallb_cp_reloader_requests_cpu
          value: "${ARGOCD_ENV_resource_metallb_cp_reloader_requests_cpu}"
        - name: resource_metallb_cp_reloader_requests_memory
          value: "${ARGOCD_ENV_resource_metallb_cp_reloader_requests_memory}"
        - name: resource_metallb_cp_reloader_limits_cpu
          value: "${ARGOCD_ENV_resource_metallb_cp_reloader_limits_cpu}"
        - name: resource_metallb_cp_reloader_limits_memory
          value: "${ARGOCD_ENV_resource_metallb_cp_reloader_limits_memory}"
        - name: resource_metallb_cp_metrics_requests_cpu
          value: "${ARGOCD_ENV_resource_metallb_cp_metrics_requests_cpu}"
        - name: resource_metallb_cp_metrics_requests_memory
          value: "${ARGOCD_ENV_resource_metallb_cp_metrics_requests_memory}"
        - name: resource_metallb_cp_metrics_limits_cpu
          value: "${ARGOCD_ENV_resource_metallb_cp_metrics_limits_cpu}"
        - name: resource_metallb_cp_metrics_limits_memory
          value: "${ARGOCD_ENV_resource_metallb_cp_metrics_limits_memory}"
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
