apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-4'
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/part-of: platform-baseline
spec:
  project: platform
  source:
    repoURL: https://github.com/KhaledSaiidi/kube-signal.git
    targetRevision: main
    path: gitops/apps/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - SkipDryRunOnMissingResource=true
