apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/part-of: platform-baseline
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/KhaledSaiidi/kube-signal.git
    targetRevision: HEAD
    path: gitops/apps/metallb
    plugin:
      name: envsubst
      env:
        - name: addresses_start
          value: "${ARGOCD_ENV_metallb_config_addresses_start}"
        - name: addresses_end
          value: "${ARGOCD_ENV_metallb_config_addresses_end}"
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
