apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
  labels:
    app.kubernetes.io/name: openebs
    app.kubernetes.io/part-of: platform-baseline
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: ${ARGOCD_ENV_gitops_root_app_repo_url}
    targetRevision: ${ARGOCD_ENV_gitops_root_app_target_revision}
    path: gitops/apps/openebs
    plugin:
      name: envsubst
      env:
        - name: openebs_version
          value: "${ARGOCD_ENV_openebs_version}"
        - name: openebs_localpv_replicas
          value: "${ARGOCD_ENV_openebs_localpv_replicas}"
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
