apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  name: reflector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: gitops/apps/reflector
    repoURL: ${ARGOCD_ENV_gitops_root_app_repo_url}
    targetRevision: ${ARGOCD_ENV_gitops_root_app_target_revision}
    plugin:
      name: envsubst
      env:
        - name: reflector_version
          value: "${ARGOCD_ENV_reflector_version}"
        - name: reflector_min_replicas
          value: "${ARGOCD_ENV_reflector_min_replicas}"
        - name: reflector_max_replicas
          value: "${ARGOCD_ENV_reflector_max_replicas}"
  destination:
    namespace: reflector
    server: https://kubernetes.default.svc
  project: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - PruneLast=true
