apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-ingress-gateway
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.5.1/standard-install.yaml
  - keep-alive.yaml
  - proxy-security-headers.yaml
helmCharts:
  - name: gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: ${ARGOCD_ENV_istio_ingress_gateway_version}
    releaseName: istio-ingress-gateway
    namespace: istio-ingress-gateway
    valuesInline:
      labels:
        app: istio-ingress-gateway
        istio: ingressgateway
