cilium_install_kubeconfig: "{{ kubeconfig_local_path | default('~/.kube/config') }}"
cilium_install_release_name: cilium
cilium_install_helm_repo_name: cilium
cilium_install_helm_repo_url: https://helm.cilium.io
cilium_install_chart_name: cilium/cilium
cilium_install_namespace: kube-system
cilium_install_chart_version: "{{ (cilium | default({})).cilium_chart_version | default('1.19.2') }}"
cilium_install_daemonset_name: cilium
cilium_install_operator_deployment_name: cilium-operator
cilium_install_hubble_relay_deployment_name: hubble-relay
cilium_install_hubble_ui_deployment_name: hubble-ui

cilium_install_image_pull_policy: "{{ (cilium | default({})).cilium_image_pull_policy | default('IfNotPresent') }}"
cilium_install_ipam_mode: "{{ (cilium | default({})).cilium_ipam_mode | default('kubernetes') }}"
cilium_install_k8s_service_host: "{{ (cilium | default({})).cilium_k8s_service_host | default('') }}"
cilium_install_k8s_service_port: "{{ (cilium | default({})).cilium_k8s_service_port | default('6443') }}"
cilium_install_kube_proxy_replacement: "{{ (cilium | default({})).cilium_kube_proxy_replacement | default(true) }}"
cilium_install_socket_lb_host_namespace_only: "{{ (cilium | default({})).cilium_socket_lb_host_namespace_only | default(true) }}"
cilium_install_cni_exclusive: "{{ (cilium | default({})).cilium_cni_exclusive | default(false) }}"
cilium_install_hubble_enabled: "{{ (cilium | default({})).cilium_hubble_enabled | default(true) }}"
cilium_install_hubble_relay_enabled: "{{ (cilium | default({})).cilium_hubble_relay_enabled | default(true) }}"
cilium_install_hubble_ui_enabled: "{{ (cilium | default({})).cilium_hubble_ui_enabled | default(true) }}"

# Readiness wait
cilium_install_wait_timeout: 600   # seconds
