cilium_install_kubeconfig: "{{ kubeconfig_local_path | default('~/.kube/config') }}"
cilium_install_release_name: cilium
cilium_install_helm_repo_name: cilium
cilium_install_helm_repo_url: https://helm.cilium.io
cilium_install_chart_name: cilium/cilium
cilium_install_namespace: kube-system
cilium_install_chart_version: 1.19.2
cilium_install_daemonset_name: cilium
cilium_install_operator_deployment_name: cilium-operator
cilium_install_hubble_relay_deployment_name: hubble-relay
cilium_install_hubble_ui_deployment_name: hubble-ui

cilium_install_image_pull_policy: IfNotPresent
cilium_install_ipam_mode: kubernetes
cilium_install_k8s_service_host: ""
cilium_install_k8s_service_port: 6443
cilium_install_kube_proxy_replacement: true
cilium_install_socket_lb_host_namespace_only: true
cilium_install_cni_exclusive: false
cilium_install_hubble_enabled: true
cilium_install_hubble_relay_enabled: true
cilium_install_hubble_ui_enabled: true

# Readiness wait
cilium_install_wait_timeout: 600   # seconds
