apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyverno
helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno
    version: ${ARGOCD_ENV_kyverno_version}
    includeCRDs: true
    releaseName: kyverno
    namespace: kyverno
    valuesFile: values.yaml
resources:
  - kyverno-background-rbac.yaml
  - kyverno-istio-default-policies.yaml
