apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: label-argocd-oidc-reflected-secret
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  admission: true
  background: true
  emitWarning: false
  validationFailureAction: Audit
  rules:
    - name: add-argocd-part-of-label
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds:
                - Secret
              namespaces:
                - argocd
              names:
                - argocd-oidc-client-secret
              operations:
                - CREATE
                - UPDATE
      preconditions:
        all:
          - key: "{{ request.object.metadata.annotations.\"reflector.v1.k8s.emberstack.com/reflects\" || '' }}"
            operator: Equals
            value: keycloak/argocd-oidc-client-secret
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              app.kubernetes.io/part-of: argocd
