admissionController:
  replicas: ${ARGOCD_ENV_kyverno_admission_controller_replicas}
  apiPriorityAndFairness: true
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  container:
    resources:
      requests:
        cpu: "${ARGOCD_ENV_resource_kyverno_admission_controller_requests_cpu}"
        memory: "${ARGOCD_ENV_resource_kyverno_admission_controller_requests_memory}"
      limits:
        cpu: "${ARGOCD_ENV_resource_kyverno_admission_controller_limits_cpu}"
        memory: "${ARGOCD_ENV_resource_kyverno_admission_controller_limits_memory}"
  metricsService:
    create: true
  serviceMonitor:
    enabled: false

backgroundController:
  replicas: ${ARGOCD_ENV_kyverno_background_controller_replicas}
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_kyverno_background_controller_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_kyverno_background_controller_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_kyverno_background_controller_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_kyverno_background_controller_limits_memory}"
  metricsService:
    create: true
  serviceMonitor:
    enabled: false

cleanupController:
  replicas: ${ARGOCD_ENV_kyverno_cleanup_controller_replicas}
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_kyverno_cleanup_controller_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_kyverno_cleanup_controller_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_kyverno_cleanup_controller_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_kyverno_cleanup_controller_limits_memory}"
  metricsService:
    create: true
  serviceMonitor:
    enabled: false

reportsController:
  replicas: ${ARGOCD_ENV_kyverno_reports_controller_replicas}
  resources:
    requests:
      cpu: "${ARGOCD_ENV_resource_kyverno_reports_controller_requests_cpu}"
      memory: "${ARGOCD_ENV_resource_kyverno_reports_controller_requests_memory}"
    limits:
      cpu: "${ARGOCD_ENV_resource_kyverno_reports_controller_limits_cpu}"
      memory: "${ARGOCD_ENV_resource_kyverno_reports_controller_limits_memory}"
  metricsService:
    create: true
  serviceMonitor:
    enabled: false
