admissionController:
  replicas: ${ARGOCD_ENV_kyverno_admission_controller_replicas}
  apiPriorityAndFairness: true
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  container:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi
  metricsService:
    create: true
  serviceMonitor:
    enabled: false

backgroundController:
  replicas: ${ARGOCD_ENV_kyverno_background_controller_replicas}
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi
  metricsService:
    create: true
  serviceMonitor:
    enabled: false

cleanupController:
  replicas: ${ARGOCD_ENV_kyverno_cleanup_controller_replicas}
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi
  metricsService:
    create: true
  serviceMonitor:
    enabled: false

reportsController:
  replicas: ${ARGOCD_ENV_kyverno_reports_controller_replicas}
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi
  metricsService:
    create: true
  serviceMonitor:
    enabled: false
