apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/name: observability
    app.kubernetes.io/part-of: observability
    ingress.apex-sync.io/public-gateway-access: "true"
    istio-injection: enabled
