apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garage
helmCharts:
  - name: garage
    repo: https://charts.derwitt.dev
    version: ${ARGOCD_ENV_garage_version}
    releaseName: garage
    namespace: garage
    valuesFile: values.yaml
resources:
  - namespace.yaml
  - internal-secrets-bootstrap-job.yaml
  - discovery-cleanup-job.yaml
  - s3-api-httproute.yaml
  - backup-bootstrap-serviceaccount.yaml
  - backup-bootstrap-rbac.yaml
  - cluster-layout-bootstrap-job.yaml
  - backup-bootstrap-job.yaml
  - backup-lifecycle-job.yaml
