replicaCount: ${ARGOCD_ENV_stateful_operator_replicas}

operatorImageRepository: percona/percona-xtradb-cluster-operator
imagePullPolicy: IfNotPresent
image: ""

nameOverride: percona-xtradb-cluster-operator
fullnameOverride: percona-xtradb-cluster-operator

watchAllNamespaces: true

rbac:
  create: true

serviceAccount:
  create: true

resources:
  requests:
    cpu: "${ARGOCD_ENV_resource_stateful_operator_requests_cpu}"
    memory: "${ARGOCD_ENV_resource_stateful_operator_requests_memory}"
  limits:
    cpu: "${ARGOCD_ENV_resource_stateful_operator_limits_cpu}"
    memory: "${ARGOCD_ENV_resource_stateful_operator_limits_memory}"

containerSecurityContext: {}

nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}

logStructured: false
logLevel: INFO
disableTelemetry: false
maxConcurrentReconciles: 1
s3WorkersLimit: 10

extraEnvVars: []

featureGates:
  xtrabackupSidecar: false
