apiVersion: openebs.io/v1beta2
kind: DiskPool
metadata:
  name: ${ARGOCD_ENV_openebs_disk_pool_1_name}
  namespace: openebs
spec:
  node: ${ARGOCD_ENV_openebs_disk_pool_1_node}
  disks:
    - ${ARGOCD_ENV_openebs_disk_pool_1_disk_uri}
---
apiVersion: openebs.io/v1beta2
kind: DiskPool
metadata:
  name: ${ARGOCD_ENV_openebs_disk_pool_2_name}
  namespace: openebs
spec:
  node: ${ARGOCD_ENV_openebs_disk_pool_2_node}
  disks:
    - ${ARGOCD_ENV_openebs_disk_pool_2_disk_uri}
---
apiVersion: openebs.io/v1beta2
kind: DiskPool
metadata:
  name: ${ARGOCD_ENV_openebs_disk_pool_3_name}
  namespace: openebs
spec:
  node: ${ARGOCD_ENV_openebs_disk_pool_3_node}
  disks:
    - ${ARGOCD_ENV_openebs_disk_pool_3_disk_uri}
