apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs
helmCharts:
  - name: openebs
    repo: https://openebs.github.io/openebs
    releaseName: openebs
    namespace: openebs
    valuesFile: openebs-values.yaml
    version: ${ARGOCD_ENV_openebs_version}
resources:
  - openebs-hostpath-setup-rbac.yaml
  - openebs-hostpath-setup.yaml
  - openebs-localpv-rbac.yaml
  - openebs-storage-class.yaml
configMapGenerator:
  - name: openebs-hostpath-setup-script
    files:
      - setup-hostpath.sh=scripts/setup-hostpath.sh
    options:
      annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/sync-wave: "-11"
        argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
generatorOptions:
  disableNameSuffixHash: true
