apiVersion: batch/v1
kind: Job
metadata:
  name: openebs-hostpath-setup-hook
  namespace: openebs
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: openebs-hostpath-setup
      restartPolicy: OnFailure
      containers:
        - name: setup
          image: bitnami/kubectl:latest
          resources:
            requests:
              cpu: "${ARGOCD_ENV_resource_openebs_hostpath_setup_requests_cpu}"
              memory: "${ARGOCD_ENV_resource_openebs_hostpath_setup_requests_memory}"
            limits:
              cpu: "${ARGOCD_ENV_resource_openebs_hostpath_setup_limits_cpu}"
              memory: "${ARGOCD_ENV_resource_openebs_hostpath_setup_limits_memory}"
          env:
            - name: OPENEBS_HOSTPATH_CHOWN_REQUESTS_CPU
              value: "${ARGOCD_ENV_resource_openebs_hostpath_chown_requests_cpu}"
            - name: OPENEBS_HOSTPATH_CHOWN_REQUESTS_MEMORY
              value: "${ARGOCD_ENV_resource_openebs_hostpath_chown_requests_memory}"
            - name: OPENEBS_HOSTPATH_CHOWN_LIMITS_CPU
              value: "${ARGOCD_ENV_resource_openebs_hostpath_chown_limits_cpu}"
            - name: OPENEBS_HOSTPATH_CHOWN_LIMITS_MEMORY
              value: "${ARGOCD_ENV_resource_openebs_hostpath_chown_limits_memory}"
          command:
            - /scripts/setup-hostpath.sh
          volumeMounts:
            - name: setup-script
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: setup-script
          configMap:
            name: openebs-hostpath-setup-script
            defaultMode: 0555
