engines:
  local:
    hostpath:
      enabled: false
    lvm:
      enabled: false
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: true

openebs-crds:
  csi:
    volumeSnapshots:
      enabled: true

alloy:
  enabled: false
loki:
  enabled: false

localpv-provisioner:
  analytics:
    enabled: false
  hostpathClass:
    enabled: false

mayastor:
  storageClass:
    enabled: false
  csi:
    node:
      initContainers:
        enabled: true
  io_engine:
    resources:
      requests:
        cpu: "${ARGOCD_ENV_resource_openebs_mayastor_io_engine_requests_cpu}"
        memory: "${ARGOCD_ENV_resource_openebs_mayastor_io_engine_requests_memory}"
      limits:
        cpu: "${ARGOCD_ENV_resource_openebs_mayastor_io_engine_limits_cpu}"
        memory: "${ARGOCD_ENV_resource_openebs_mayastor_io_engine_limits_memory}"
  etcd:
    clusterDomain: cluster.local
  localpv-provisioner:
    enabled: false
  crds:
    enabled: false
  loki:
    enabled: false
  alloy:
    enabled: false
