engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: false
alloy:
  enabled: false
loki:
  enabled: false
localpv-provisioner:
  analytics:
    enabled: false
  hostpathClass:
    enabled: false
  localpv:
    enabled: true
    basePath: /var/openebs/kube-signal
    replicas: ${ARGOCD_ENV_openebs_localpv_replicas}
    resources:
      requests:
        cpu: "${ARGOCD_ENV_resource_openebs_localpv_requests_cpu}"
        memory: "${ARGOCD_ENV_resource_openebs_localpv_requests_memory}"
      limits:
        cpu: "${ARGOCD_ENV_resource_openebs_localpv_limits_cpu}"
        memory: "${ARGOCD_ENV_resource_openebs_localpv_limits_memory}"
