engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: false
alloy:
  enabled: false
loki:
  enabled: false
localpv-provisioner:
  analytics:
    enabled: false
  hostpathClass:
    enabled: false
  localpv:
    enabled: true
    basePath: /var/openebs/kube-signal
    replicas: 1
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
