# Kubernetes access
argocd_install_kubeconfig: "{{ kubeconfig_local_path | default('~/.kube/config') }}"
argocd_install_values_local_path: "{{ artifacts.argocd_values_local_path | default('') }}"

# Chart settings
argocd_install_namespace: argocd
argocd_install_create_namespace: true
argocd_install_helm_repo_name: argo
argocd_install_helm_repo_url: https://argoproj.github.io/argo-helm
argocd_install_chart_name: argo/argo-cd
argocd_install_chart_version: "{{ argocd.argocd_chart_version }}"
argocd_install_release_name: argocd
argocd_install_server_deployment_name: argocd-server
argocd_install_repo_server_deployment_name: argocd-repo-server
argocd_install_application_controller_statefulset_name: argocd-application-controller
# Readiness wait
argocd_install_wait_timeout: 600   # seconds
