apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
  labels:
    app.kubernetes.io/name: istiod
    app.kubernetes.io/instance: istiod
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: observability
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - istio-system
  selector:
    matchLabels:
      app.kubernetes.io/name: istiod
      app.kubernetes.io/instance: istiod
  endpoints:
    - port: http-monitoring
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
