apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: public-gateway
  labels:
    app.kubernetes.io/name: public-gateway
    app.kubernetes.io/instance: public-gateway
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: observability
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - istio-ingress
  selector:
    matchLabels:
      app.kubernetes.io/name: public-gateway
      app.kubernetes.io/instance: public-gateway
  endpoints:
    - targetPort: http-envoy-prom
      path: /stats/prometheus
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
