apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stateful-operator
  labels:
    app.kubernetes.io/name: percona-xtradb-cluster-operator
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: observability
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - stateful-operator
  selector:
    matchLabels:
      app.kubernetes.io/name: percona-xtradb-cluster-operator
      app.kubernetes.io/component: metrics
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
