apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-main
helmCharts:
  - name: istio-main
    repo: https://kubernetes-sigs.github.io/istio-main
    releaseName: istio-main
    namespace: istio-main

