replicaCount: ${ARGOCD_ENV_istiod_replicas}

resources:
  requests:
    cpu: "${ARGOCD_ENV_resource_istiod_requests_cpu}"
    memory: "${ARGOCD_ENV_resource_istiod_requests_memory}"
  limits:
    cpu: "${ARGOCD_ENV_resource_istiod_limits_cpu}"
    memory: "${ARGOCD_ENV_resource_istiod_limits_memory}"

meshConfig:
  accessLogFile: /dev/stdout

global:
  proxy:
    holdApplicationUntilProxyStarts: true
