replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi

meshConfig:
  accessLogFile: /dev/stdout

global:
  proxy:
    holdApplicationUntilProxyStarts: true
