apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reflector
helmCharts:
  - name: reflector
    repo: oci://ghcr.io/emberstack/helm-charts/reflector
    version: ${ARGOCD_ENV_reflector_version}
    releaseName: reflector
    namespace: reflector
    valuesFile: values.yaml

