autoscaling:
  enabled: true
  minReplicas: ${ARGOCD_ENV_reflector_min_replicas}
  maxReplicas: ${ARGOCD_ENV_reflector_max_replicas}
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  requests:
    cpu: "${ARGOCD_ENV_resource_reflector_requests_cpu}"
    memory: "${ARGOCD_ENV_resource_reflector_requests_memory}"
  limits:
    cpu: "${ARGOCD_ENV_resource_reflector_limits_cpu}"
    memory: "${ARGOCD_ENV_resource_reflector_limits_memory}"
