autoscaling:
  enabled: true
  minReplicas: ${ARGOCD_ENV_reflector_min_replicas}
  maxReplicas: ${ARGOCD_ENV_reflector_max_replicas}
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
