provider:
  name: aws

env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: route53-credentials-secret
        key: aws_access_key_id
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: route53-credentials-secret
        key: aws_secret_access_key
  - name: AWS_DEFAULT_REGION
    value: ${ARGOCD_ENV_cert_manager_route53_region}

sources:
  - gateway-httproute

domainFilters:
  - ${ARGOCD_ENV_base_domain}

policy: sync
registry: txt
txtOwnerId: ${ARGOCD_ENV_external_dns_txt_owner_id}
interval: 1m
triggerLoopOnEvent: true
logLevel: info

serviceAccount:
  create: true

resources:
  requests:
    cpu: "${ARGOCD_ENV_resource_external_dns_requests_cpu}"
    memory: "${ARGOCD_ENV_resource_external_dns_requests_memory}"
  limits:
    cpu: "${ARGOCD_ENV_resource_external_dns_limits_cpu}"
    memory: "${ARGOCD_ENV_resource_external_dns_limits_memory}"

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
