apiVersion: v1
kind: Secret
metadata:
  name: mysql-cluster-haproxy-env
type: Opaque
stringData:
  HA_CONNECTION_TIMEOUT: "60000"
  HA_SERVER_OPTIONS: "check inter 30000 rise 1 fall 5 weight 1 on-marked-down shutdown-sessions"
  VERBOSE: "0"
