apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stateful-resources
resources:
  - priority-class.yaml
  - pg-app-credentials-bootstrap-rbac.yaml
  - pg-app-credentials-bootstrap-job.yaml
helmCharts:
  - name: pxc-db
    repo: https://percona.github.io/percona-helm-charts
    version: ${ARGOCD_ENV_percona_version}
    releaseName: mysql-cluster
    namespace: stateful-resources
    valuesFile: values.yaml
  - name: pg-db
    repo: https://percona.github.io/percona-helm-charts
    version: ${ARGOCD_ENV_percona_pg_version}
    releaseName: pg-cluster
    namespace: stateful-resources
    valuesFile: values-pg.yaml
configMapGenerator:
  - name: pg-app-credentials-bootstrap-script
    files:
      - reflect-pg-app-credentials.sh=scripts/reflect-pg-app-credentials.sh
generatorOptions:
  disableNameSuffixHash: true
