apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: mysql-cluster
  labels:
    app.kubernetes.io/name: mysql-cluster
    app.kubernetes.io/part-of: stateful-resources
  finalizers:
    - percona.com/delete-pxc-pods-in-order
spec:
  crVersion: ${ARGOCD_ENV_percona_version}
  secretsName: mysql-cluster-secrets
  tls:
    enabled: true
  updateStrategy: SmartUpdate
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: disabled
    schedule: "0 4 * * *"
  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.4.7-7.1
    autoRecovery: true
    readinessProbes:
      initialDelaySeconds: 15
      timeoutSeconds: 15
      periodSeconds: 30
      successThreshold: 1
      failureThreshold: 5
    livenessProbes:
      initialDelaySeconds: 300
      timeoutSeconds: 5
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    containerSecurityContext:
      privileged: false
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      supplementalGroups:
        - 1001
    resources:
      requests:
        memory: 400Mi
        cpu: 300m
        ephemeral-storage: 1G
      limits:
        memory: 1536Mi
        cpu: "1"
        ephemeral-storage: 1G
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: percona-xtradb-cluster
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    podDisruptionBudget:
      maxUnavailable: 1
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: openebs-storage-class
        resources:
          requests:
            storage: 10G
    gracePeriod: 600
  haproxy:
    enabled: true
    size: 3
    image: percona/haproxy:2.8.17
    readinessProbes:
      initialDelaySeconds: 15
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    livenessProbes:
      initialDelaySeconds: 60
      timeoutSeconds: 5
      periodSeconds: 30
      successThreshold: 1
      failureThreshold: 4
    exposePrimary:
      type: ClusterIP
    exposeReplicas:
      enabled: true
      onlyReaders: true
      type: ClusterIP
    resources:
      requests:
        memory: 400Mi
        cpu: 300m
      limits:
        memory: 1536Mi
        cpu: 800m
    priorityClassName: high-priority
    containerSecurityContext:
      privileged: false
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      supplementalGroups:
        - 1001
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: percona-xtradb-cluster
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
    affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    podDisruptionBudget:
      maxUnavailable: 1
    gracePeriod: 30
  logcollector:
    enabled: true
    image: percona/fluentbit:4.0.1-1
    resources:
      requests:
        memory: 100M
        cpu: 200m
  backup:
    image: percona/percona-xtrabackup:8.4.0-5.1
    pitr:
      enabled: true
      storageName: garage-binlogs
      timeBetweenUploads: 60
      timeoutSeconds: 60
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 1Gi
          cpu: 700m
    storages:
      garage-full:
        type: s3
        verifyTLS: true
        resources:
          requests:
            memory: 512Mi
            cpu: 300m
          limits:
            memory: 1Gi
            cpu: 700m
        containerSecurityContext:
          privileged: false
        podSecurityContext:
          runAsUser: 1001
          runAsGroup: 1001
          supplementalGroups:
            - 1001
        s3:
          bucket: percona-backups/full
          credentialsSecret: percona-backup-garage-s3
          endpointUrl: https://garage-s3.${ARGOCD_ENV_base_domain}
          region: garage
      garage-binlogs:
        type: s3
        verifyTLS: true
        labels:
          app.kubernetes.io/name: mysql-cluster-backup
          app.kubernetes.io/component: backup-pitr
          app.kubernetes.io/part-of: stateful-resources
        containerSecurityContext:
          privileged: false
        s3:
          bucket: percona-backups/binlogs
          credentialsSecret: percona-backup-garage-s3
          endpointUrl: https://garage-s3.${ARGOCD_ENV_base_domain}
          region: garage
    schedule:
      - name: daily-full-backup
        schedule: "0 0 * * *"
        storageName: garage-full
  passwordGenerationOptions:
    symbols: "!#$%&()+,-.<=>?@[]^_{}~"
    maxLength: 16
    minLength: 12
