fullnameOverride: mysql-cluster

finalizers:
  - percona.com/delete-pxc-pods-in-order

crVersion: ${ARGOCD_ENV_percona_version}

tls:
  enabled: true

updateStrategy: SmartUpdate

upgradeOptions:
  versionServiceEndpoint: https://check.percona.com
  apply: disabled
  schedule: "0 4 * * *"

pxc:
  clusterSecretName: mysql-cluster-secrets
  certManager: true
  size: 3
  autoRecovery: true
  tolerations:
    - operator: Exists
  resources:
    requests:
      memory: 384Mi
      cpu: 150m
      ephemeral-storage: 1G
    limits:
      memory: 1536Mi
      cpu: "1"
      ephemeral-storage: 1G
  topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/name: percona-xtradb-cluster
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
  affinity:
    antiAffinityTopologyKey: kubernetes.io/hostname
  podDisruptionBudget:
    maxUnavailable: 1
  persistence:
    enabled: true
    storageClass: openebs-storage-class
    accessMode: ReadWriteOnce
    size: 20Gi
  gracePeriod: 600
  readinessProbes:
    initialDelaySeconds: 15
    timeoutSeconds: 15
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 5
  livenessProbes:
    initialDelaySeconds: 300
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  containerSecurityContext:
    privileged: false
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 1001
    supplementalGroups:
      - 1001

haproxy:
  enabled: true
  size: 3
  exposePrimary:
    type: ClusterIP
  exposeReplicas:
    enabled: true
    onlyReaders: true
    type: ClusterIP
  resources:
    requests:
      memory: 512Mi
      cpu: 600m
    limits:
      memory: 512Mi
  envVarsSecret: mysql-cluster-haproxy-env
  priorityClassName: high-priority
  tolerations:
    - operator: Exists
  topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/name: percona-xtradb-cluster
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
  affinity:
    antiAffinityTopologyKey: kubernetes.io/hostname
  podDisruptionBudget:
    maxUnavailable: 1
  gracePeriod: 30
  readinessProbes:
    initialDelaySeconds: 15
    timeoutSeconds: 1
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  livenessProbes:
    initialDelaySeconds: 60
    timeoutSeconds: 5
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 4
  containerSecurityContext:
    privileged: false
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 1001
    supplementalGroups:
      - 1001

proxysql:
  enabled: false

logcollector:
  enabled: true
  resources:
    requests:
      memory: 64Mi
      cpu: 25m
    limits:
      memory: 128Mi
      cpu: 100m

backup:
  enabled: true
  pitr:
    enabled: true
    storageName: garage-binlogs
    timeBetweenUploads: 60
    timeoutSeconds: 60
    resources:
      requests:
        memory: 64Mi
        cpu: 25m
      limits:
        memory: 256Mi
        cpu: 200m
  storages:
    garage-full:
      type: s3
      verifyTLS: true
      resources:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 512Mi
          cpu: 300m
      containerSecurityContext:
        privileged: false
      podSecurityContext:
        runAsUser: 1001
        runAsGroup: 1001
        supplementalGroups:
          - 1001
      s3:
        bucket: percona-backups/full
        credentialsSecret: percona-backup-garage-s3
        endpointUrl: https://garage-s3.${ARGOCD_ENV_base_domain}
        region: garage
    garage-binlogs:
      type: s3
      verifyTLS: true
      labels:
        app.kubernetes.io/name: mysql-cluster-backup
        app.kubernetes.io/component: backup-pitr
        app.kubernetes.io/part-of: stateful-resources
      containerSecurityContext:
        privileged: false
      s3:
        bucket: percona-backups/binlogs
        credentialsSecret: percona-backup-garage-s3
        endpointUrl: https://garage-s3.${ARGOCD_ENV_base_domain}
        region: garage
  schedule:
    - name: daily-full-backup
      schedule: "0 0 * * *"
      storageName: garage-full

passwordGenerationOptions:
  symbols: "!#$%&()+,-.<=>?@[]^_{}~"
  maxLength: 16
  minLength: 12
