apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
helmCharts:
  - name: keycloak
    repo: oci://registry-1.docker.io/bitnamicharts/keycloak
    version: ${ARGOCD_ENV_keycloak_chart_version}
    releaseName: keycloak
    namespace: keycloak
    valuesFile: values.yaml
resources:
  - namespace.yaml
  - 'https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/${ARGOCD_ENV_keycloak_operator_version}/kubernetes/kubernetes.yml'
  - keycloak-httproute.yaml