apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  finalizers:
  - operator.grafana.com/finalizer
  name: loki
  namespace: observability
spec:
  allowCrossNamespaceImport: false
  datasource:
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      httpHeaderName1: X-Scope-OrgID
      timeout: 60
    name: Loki
    secureJsonData:
      httpHeaderValue1: "1"
    type: loki
    url: http://loki-gateway.observability.svc.cluster.local
  instanceSelector:
    matchLabels:
      dashboards: grafana
  resyncPeriod: 10m0s