apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  finalizers:
  - operator.grafana.com/finalizer
  generation: 1
  name: tempo
  namespace: observability
spec:
  allowCrossNamespaceImport: false
  datasource:
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      httpHeaderName1: X-Scope-OrgID
      lokiSearch:
        datasourceUid: Loki
      nodeGraph:
        enabled: true
      search:
        hide: false
      serviceMap:
        datasourceUid: Prometheus
      spanBar:
        tag: http.path
        type: Tag
      traceQuery:
        spanEndTimeShift: 1h
        spanStartTimeShift: -1h
        timeShiftEnabled: true
      tracesToLogsV2:
        customQuery: true
        datasourceUid: Loki
        filterBySpanID: false
        filterByTraceID: false
        spanEndTimeShift: 1h
        spanStartTimeShift: -1h
        tags:
        - job
        - instance
        - pod
        - namespace
    name: Tempo
    type: tempo
    url: http://tempo-grafana-tempo-query-frontend:3200
  instanceSelector:
    matchLabels:
      dashboards: grafana
  plugins:
    - name: grafana-exploretraces-app
      version: 2.0.3
  resyncPeriod: 10m0s
